version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-api
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - media_data:/tmp/media_uploads
      - processing_data:/tmp/media_processing
    depends_on:
      - redis
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery-worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - media_data:/tmp/media_uploads
      - processing_data:/tmp/media_processing
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always

volumes:
  media_data:
  processing_data:
